### ISSUE TITLE
Markup text in log messages does not render correctly

### ISSUE THREAD

**Issue by dgosbell** [lucadecamillis/Serilog.Sinks.SpectreConsole#3]
Currently if you have inline markup in your log messages it does not render correctly
![image](https://user-images.githubusercontent.com/8241830/232987236-ecd4ad54-2dee-4b5a-8820-2493dd539d5e.png)
I have a fix for this in my local fork if you would be interested in a pull request.

**Comment by lucadecamillis** [comment]
Hi, sorry for the late replay, I saw the message but I was in the middle of smt and I forgot. You're more than welcome to submit a PR and I see you just did. I will check it and approve it asap.

**Comment by lucadecamillis** [comment]
Pull request merged into master
